%A demo script file to show the use of analytic_sod.m
time = 0.25;
data = analytic_sod(time);
figure
plot(data.x,data.rho,'-b','LineWidth',2);
xlabel({'$x$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
ylabel({'$\rho$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
title('$t = 0.25$ Density vs Position','FontUnits','points','interpreter','latex',...
    'FontSize',9);
set(gca,'Units','normalized','Position',[.1 .1 .6 .4],...
    'FontUnits','points','FontWeight','normal','FontSize',9)
print -depsc2 sod1.eps


figure
plot(data.x,data.P,'-g','LineWidth',2);
xlabel({'$x$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
ylabel({'$p$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
title('Plot of Pressure vs Position','FontUnits','points','interpreter','latex',...
    'FontSize',9);
set(gca,'Units','normalized','Position',[.1 .1 .6 .4],...
    'FontUnits','points','FontWeight','normal','FontSize',9)
print -depsc2 sod2.eps

figure
plot(data.x,data.u,'-r','LineWidth',2);
xlabel({'$x$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
ylabel({'$u$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
title('$t = 0.25$ Velocity vs Position','FontUnits','points','interpreter','latex',...
    'FontSize',9);
set(gca,'Units','normalized','Position',[.1 .1 .6 .4],...
    'FontUnits','points','FontWeight','normal','FontSize',9)
print -depsc2 sod3.eps

figure
plot(data.x,data.e,'-k','LineWidth',2);
xlabel({'$x$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
ylabel({'$E$'},'FontUnits','points','interpreter','latex',...
    'FontSize',9);
title('$t = 0.25$ Internal Energy vs Position','FontUnits','points','interpreter','latex',...
    'FontSize',9);
set(gca,'Units','normalized','Position',[.1 .1 .6 .4],...
    'FontUnits','points','FontWeight','normal','FontSize',9)
print -depsc2 sod4.eps

